# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    - feature/*
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: PHP Composer
      # You may pin to the exact commit or the version.
      # uses: baschny/php-composer-action@93b5aef92179c5ebba8824db8d34748301c6a70e
        uses: baschny/php-composer-action@v1
        with:
          # What version of Composer to use
          composer_version: latest # optional, default is latest
          # Composer command to run (or get_config to just get the output vars)
          command: install # default is install
          # Command line arguments to composer
          #args: # optional, default is --optimize-autoloader --no-progress
          # OAuth token for accessing github private resources
          #github_oauth: # optional, default is 
          php_version: 7.4.9
          
